# Generated by Django 4.1.3 on 2023-05-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='places.place')),
                ('users', models.ManyToManyField(related_name='liked_places', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='places.place')),
                ('users', models.ManyToManyField(related_name='disliked_places', to='users.user')),
            ],
        ),
    ]
