# Generated by Django 4.1.3 on 2023-04-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='place',
            table='seoul',
        ),
    ]
